name: springing
server:
  port: 8181
spring:
  data:
    mongodb:
      #uri: mongodb://192.168.1.3:27017/springing
      uri: mongodb://localhost:27017/springing
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
